@baseUrl = http://localhost:3333
@student_email = {{create_account_students.request.body.email}}
@instructor_email = {{create_account_instructor.request.body.email}}
@authToken = {{authenticate.response.body.token}}
@courseId = {{create_course.response.body.id}}
@categoryName = {{create_course.response.body.category}}

# @name create_account_students
POST {{baseUrl}}/accounts/students
Content-Type: application/json

{
    "name": "Lucas Rodrigues",
    "email": "lucas@student.com.br",
    "password": "123456",
    "cpf": "11111411113",
    "phoneNumber": "1223"
}

###

# @name get_student
GET {{baseUrl}}/students/d903ff3c-8990-4e6c-9521-0e5de4a0ffe0
Content-Type: application/json

###

# @name create_account_instructor
POST {{baseUrl}}/accounts/instructors
Content-Type: application/json

{
    "name": "Claudio Silva",
    "bio": "Graduado em Ciencia da Computacao",
    "email": "Claudio@instructor.com.br",
    "passwordHash": "123456",
    "cpf": "11141451112",
    "phoneNumber": "12743"
}

###

# @name get_instructor
GET {{baseUrl}}/instructors/36eebcc4-9f6a-4c9c-9467-aadb6484bd15
Content-Type: application/json

###

# @name authenticate
POST {{baseUrl}}/sessions/students
Content-Type: application/json

{
    "email": "{{student_email}}",
    "password": "123456"
}

###

# @name get_student_profile
GET {{baseUrl}}/students/d903ff3c-8990-4e6c-9521-0e5de4a0ffe0/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name authenticate
POST {{baseUrl}}/sessions/instructors
Content-Type: application/json

{
    "email": "{{instructor_email}}",
    "password": "123456"
}

###

# @name get_instructor_profile
GET {{baseUrl}}/instructors/36eebcc4-9f6a-4c9c-9467-aadb6484bd15/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_course
POST {{baseUrl}}/instructors/course
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Curso Design 888",
    "description": "Apenas um teste",
    "thumbnailUrl": "Apenas um teste",
    "price": 15,
    "duration": 60,
    "categoryId": 2,
    "level": "BEGINNER"
}

###

# @name publish_course
PATCH {{baseUrl}}/instructors/course/publish/{{courseId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_courses
GET {{baseUrl}}/courses
Content-Type: application/json

###

# @name fetch_courses_by_category
GET {{baseUrl}}/courses/category?categoryName={{categoryName}}&page=1&limit=20
Content-Type: application/json

###

# @name get_course_by_slug
GET {{baseUrl}}/courses/slug/curso-design
Content-Type: application/json

###

# @name get_course
GET {{baseUrl}}/courses/{{courseId}}
Content-Type: application/json

###

# @name delete_course
DELETE {{baseUrl}}/instructors/course/{{courseId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name request_enroll_student
POST {{baseUrl}}/students/course/{{courseId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
