volumes:
  mysql_elearning:

services:
  mysql:
    image: mysql
    container_name: mysql_elearning_local
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
      MYSQL_DATABASE: 'elearning'
    ports:
      - 5432:5432
    volumes:
      - mysql_elearning:/data/mysql